spring.profiles.active=development

spring.application.name=strivo-labs-assessment-java

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# let flyway handle schema creation
# correct - value only, comment on separate line
# only validates entities match DB, never changes it
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# flyway config
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations
spring.flyway.baseline-on-migrate=true

# outbox processing config
outbox.scheduler.delay-ms=15000
outbox.batch-size=20
outbox.max-retries=3
outbox.retry-delay-seconds=30

# mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# jwt config
security.jwt.private-key=
security.jwt.public-key=
security.jwt.access-token-expiration-ms=900000
security.jwt.refresh-token-expiration-days=7
security.jwt.issuer=
security.jwt.audience=

# one time token config
security.email-confirmation-token-expiration-ms=900000

# session config
security.session-expiration-days=7

# lockout config
security.lockout.max-failed-attempts=3
security.lockout.base-lockout-in-minutes=15
security.lockout.multiplier=2.0
security.lockout.max-lockout-minutes=1440

# hashing config
security.hashing.keys[0].key-id=v1
security.hashing.keys[0].secret=
security.hashing.keys[0].is-active=true

# endpoints
confirm-email-endpoint=